# oh-my-zsh
export ZSH="/Users/alanlau/.oh-my-zsh"
ZSH_THEME="melaus"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# listing aliases
alias l="ls -l"
alias ll="ls -la"
# alias ls="ls --color=auto"
# alias l="ls -lhX"
# alias ll="ls -alhX"
# alias la="ls -alhX"
# alias c="cd -P"
# alias grep="grep --color"


# vim mode in zsh!
bindkey -v
bindkey '^R' history-incremental-search-backward
bindkey '^F' history-incremental-search-forward
bindkey -M vicmd '/' history-incremental-pattern-search-backward
bindkey -M vicmd '?' history-incremental-pattern-search-forward
# bindkey '^R' history-incremental-search-backward
# bindkey "^?" backward-delete-char # fix vim insert mode backspace


# export PATH
#export PATH="$PATH"


alias vscode="open -a \"Visual Studio Code\" $1"
alias pycharm="open -a \"PyCharm\" $1"
alias idea="open -a \"IntelliJ IDEA CE\" $1"
